### ISSUE TITLE
NodeJS v4.0.0 fails using Vagrant (Linux)

### ISSUE THREAD

**Issue by jakejackson1** [thecodingmachine/nodejs-installer#21] opened 2015-09-16 06:57 UTC
After experiencing issue #20 I tried on a Vagrant box I have set up but had issues extracting the package with TAR. The following was my output:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
Installing NodeJS v4.0.0
  Downloading from https://nodejs.org/dist/v4.0.0/node-v4.0.0-linux-x64.tar.gz
    Downloading: Connecting...
    Downloading: 0%           
    Downloading: 100%
tar: lib/node_modules/npm/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/node_modules/generate-object-property/node_modules/is-property: Cannot mkdir: Protocol error
tar: lib/node_modules/npm/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/node_modules/generate-object-property/node_modules/is-property: Cannot mkdir: Protocol error
tar: lib/node_modules/npm/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/node_modules/generate-object-property/node_modules/is-property/is-property.js: Cannot open: No such file or directory
tar: lib/node_modules/npm/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/node_modules/generate-object-property/node_modules/is-property: Cannot mkdir: Protocol error
tar: lib/node_modules/npm/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/node_modules/generate-object-property/node_modules/is-property/package.json: Cannot open: No such file or directory
tar: lib/node_modules/npm/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/node_modules/generate-object-property/node_modules/is-property: Cannot mkdir: Protocol error
tar: lib/node_modules/npm/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/node_modules/generate-object-property/node_modules/is-property/LICENSE: Cannot open: No such file or directory
tar: lib/node_modules/npm/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/node_modules/generate-object-property/node_modules/is-property: Cannot mkdir: Protocol error
tar: lib/node_modules/npm/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/node_modules/generate-object-property/node_modules/is-property/README.md: Cannot open: No such file or directory
tar: lib/node_modules/npm/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/node_modules/generate-object-property/node_modules/is-property: Cannot mkdir: Protocol error
tar: lib/node_modules/npm/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/node_modules/generate-object-property/node_modules/is-property/.npmignore: Cannot open: No such file or directory
tar: bin/npm: Cannot create symlink to ‘../lib/node_modules/npm/bin/npm-cli.js’: Protocol error
tar: Exiting with failure status due to previous errors



  [Mouf\NodeJsInstaller\NodeJsInstallerException]                              
  An error occurred while untaring NodeJS (vendor/node-v4.0.0-linux-x64.tar.g  
  z) to vendor/nodejs/nodejs                         
```

**Comment by moufmouf** [comment] 2015-09-16 08:20
Hi Jake,

What the f**k! Last time I checked, Node was in version 0.12... and now, we bump directly to 4.0!

Anyway, this issue seems to be related to Vagrant rather than nodejs-installer. Basically, the "tar" command seems to be trying to create symlinks, but since you are using Vagrant, the filesystem is NTFS, and NTFS supports symlinks in a very special way (I believe you need to be administrator).

Check out this issue: http://stackoverflow.com/questions/28755845/npm-install-within-vagrant-box

I'm pretty sure the problem is directly related. Could you have a look at the fix in the link above and let me know if it works?

In other news, a fix for NodeJS 4.0 for Windows version is coming.

**Comment by moufmouf** [comment] 2015-09-16 08:55
I'm closing this issue as this seems to be Node / Vagrant related.

**Closed as completed by moufmouf** 2015-09-16 08:55 UTC

**Comment by jakejackson1** [comment] 2015-09-16 23:49
Fair enough. Thanks for the follow up.
